import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { LoginBtn, LogoutBtn } from './LogBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import DarkMode from './DarkMode';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);
    // console.log(session);

    let res = cookies().get('mode');
    console.log(res);

    return (
        <html lang="en">
            {/* mode=dark인 경우 dark-mode 클래스명 부착하면 될 듯 */}
            <body className={res !== undefined && res.value === 'dark' ? 'dark-mode' : ''}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        AppleForum
                    </Link>
                    <Link href="/list">List</Link>
                    {session ? (
                        <span>
                            {`Welcome` + ' ' + session.user.name + '!'}
                            <LogoutBtn />
                        </span>
                    ) : (
                        <LoginBtn />
                    )}
                    <DarkMode />
                </div>
                {children}
            </body>
        </html>
    );
}
